# Generated by Django 4.2.4 on 2023-10-12 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='TrainedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.trainer'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectMembershipplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authapp.membershipplan'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectTrainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.trainer'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
