# Generated by Django 4.2.4 on 2023-10-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_attendance_trainedby_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='TrainedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.trainer'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='SelectTrainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.trainer'),
        ),
    ]
